version: '2.1'

networks:
  mynetwork:
      driver: bridge
    
volumes:
  db_data:

services:

    service_mysql:
        container_name: cnt-mysql
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - './init.sql:/docker-entrypoint-initdb.d/init.sql'
            - 'db_data:/var/lib/mysql'
        restart: always
        networks:
            - mynetwork
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=db_warren
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=warren2020
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=admin --execute \"SHOW DATABASES;\""

    service_mysql_admin:
        container_name: cnt-mysql-admin
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - mynetwork
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1

    # service_api:
    #     container_name: cnt-api
    #     image: 'cnt-api:latest'
    #     ports:
    #         - '5000:80'
    #     depends_on:
    #         service_mysql:
    #             condition: service_healthy
    #     build:
    #         context: .
    #         dockerfile: desafio.warren.webapi/Dockerfile
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    #     networks:
    #         - mynetwork